.github/workflows/storybook-master-push.yml
.github/workflows/storybook-pr-sync.yml
client/components/ExampleComponent/ExampleComponent.stories.tsx

ci(client): setup github action for storybook

---

.travis.yml
client/components/ExampleComponent/ExampleComponent.test.tsx
client/components/ExampleComponent/__snapshots__/ExampleComponent.test.tsx.snap
client/jest.config.js
client/jest.setup.ts
client/package.json
client/tsconfig.jest.json
package.json
yarn.lock

feat(client): add test script

---

.github/workflows/client-now-pr-deploy.yml
client/pages/index.tsx
now.json

ci(client): setup zeit deployment

---

.github/auto_assign.yml
.github/workflows/auto-assign-reviewers.yml

ci(client): auto assign reviewers github action

---

.github/workflows/client-now-master-push.yml
.github/workflows/client-now-pr-deploy.yml
now.json

Fix issue mentioned in https://github.com/zeit/now-builders/issues/811

ci(client): fix dynamic routes deploy 404

---

client/components/Card/Card.stories.tsx
client/components/Card/index.tsx
client/components/Sidebar/index.tsx
client/pages/[communityname]/[channelname]/[post]/index.tsx
client/pages/[communityname]/[channelname]/index.tsx
client/pages/[communityname]/index.tsx
client/pages/users/[username]/index.tsx
client/tailwind.js

feat(client): update card component

---

client/next.config.js
client/package.json
client/pages/_app.tsx
client/pages/index.tsx
client/tailwind.js
client/utils/notifications.tsx
yarn.lock

feat(client): add toast notification

---

client/components/Spinner/Spinner.stories.tsx
client/components/Spinner/index.tsx
client/styles/index.css

feat(client): add spinner component

---

client/babel-plugin-macros.config.js
client/components/ExampleComponent/__snapshots__/ExampleComponent.test.tsx.snap

fix(client): storybook tailwind macro not apply

---

client/components/Input/Input.stories.tsx
client/components/Input/index.tsx
client/components/form/FormInput/FormInput.stories.tsx
client/components/form/FormInput/index.tsx
client/components/form/createFormElement.tsx
client/package.json
yarn.lock

Add input component

---

client/components/Textarea/Textarea.stories.tsx
client/components/Textarea/index.tsx
client/components/form/FormTextarea/FormTextarea.stories.tsx
client/components/form/FormTextarea/index.tsx

feat(client): add textarea component

---

client/components/Checkbox/Checkbox.stories.tsx
client/components/Checkbox/index.tsx
client/components/form/FormCheckbox/FormCheckbox.stories.tsx
client/components/form/FormCheckbox/index.tsx
client/components/icons/createIcon.tsx

feat(client): add checkbox form

---

client/.storybook/config.js
client/.storybook/webpack.config.js
client/components/Avatar/CommunityAvatar.tsx
client/components/Avatar/UserAvatar.tsx
client/components/Avatar/index.tsx
client/components/Avatar/styles.tsx
client/components/ExampleComponent/__snapshots__/ExampleComponent.test.tsx.snap
client/components/ExampleComponent/index.tsx
client/components/ProfileCard/Community.tsx
client/components/ProfileCard/CommunityActions.tsx
client/components/ProfileCard/CommunityMeta.tsx
client/components/ProfileCard/ProfileCard.stories.tsx
client/components/ProfileCard/User.tsx
client/components/ProfileCard/UserActions.tsx
client/components/ProfileCard/UserMeta.tsx
client/components/ProfileCard/index.tsx
client/components/ProfileCard/styles.tsx
client/package.json
client/pages/[communityname]/[channelname]/index.tsx
client/pages/[communityname]/index.tsx
client/pages/users/[username]/index.tsx
yarn.lock

feat(client): create community and user card

---

client/components/Checkbox/index.tsx
client/components/Input/index.tsx
client/components/MenuItem/MenuItem.stories.tsx
client/components/MenuItem/index.tsx
client/components/Sidebar/CommunityBadge/index.tsx
client/components/Sidebar/SidebarMenuItem/SidebarMenuItem.stories.tsx
client/components/Sidebar/SidebarMenuItem/index.tsx
client/components/Sidebar/index.tsx
client/components/Spinner/index.tsx
client/components/Textarea/index.tsx
client/components/form/FormInput/FormInput.stories.tsx
client/components/form/FormTextarea/FormTextarea.stories.tsx
client/pages/explore/index.tsx
client/pages/index.tsx
client/tailwind.js

feat(client): add menuItem component

---

client/components/ThreadItem/Thread.stories.tsx
client/components/ThreadItem/index.tsx
client/pages/[communityname]/index.tsx

feat(client): add ThreadItem component

---

client/components/Select/Select.stories.tsx
client/components/Select/index.tsx
client/components/form/FormSelect/FormSelect.stories.tsx
client/components/form/FormSelect/index.tsx

feat(client): add select component

---

client/components/ChannelMenuItem/ChannelMenuItem.stories.tsx
client/components/ChannelMenuItem/index.tsx
client/components/community/ChannelsCard/index.tsx
client/pages/[communityname]/[channelname]/[post]/index.tsx
client/pages/[communityname]/[channelname]/index.tsx
client/pages/[communityname]/index.tsx

feat(client): add ChannelMenuItem component

---

client/components/Tabs/Tabs.stories.tsx
client/components/Tabs/index.tsx

feat(client): add tabs component

---

client/components/form/CoverAndAvatarUploader/CoverAndAvatarUploader.stories.tsx
client/components/form/CoverAndAvatarUploader/index.tsx

feat(client): add cover and avatar uploader component

---

client/components/InlineInput/InlineInput.stories.tsx
client/components/InlineInput/index.tsx
client/components/form/FormInlineInput/FormInput.stories.tsx
client/components/form/FormInlineInput/index.tsx

feat(client): add InlineInput component
